# This is a basic workflow to help you get started with Actions

name: Deploy to Staging

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max_old_space_size=6144
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-2
      AWS_DEFAULT_OUTPUT: json
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Fetch current staging task
        run: |
          ARN=$(aws ecs list-tasks --cluster "Ophanim2" --service "TDANophanim-staging-Service" --output text --query taskArns[0])
          echo "::set-output name=arn::$ARN"
        id: fetch
      
      - name: Stop current staging task
        run: |
          aws ecs stop-task --cluster "Ophanim2" --task "${{ steps.fetch.outputs.arn }}"
