name: Ophanim Tag CI

on:
  push:
#    branches: [ beta, dev, docker, qa, k8s ]
#     branches: [ k8s ]
    tags:
    - '*'     
#  pull_request:
#    branches: [ beta, dev, docker, qa, k8s ]
#     branches: [ k8s ]

jobs: 
  build:

    env:
      NODE_OPTIONS: --max_old_space_size=6144
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      BUILD_BRANCH: k8s
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      
      - name: Cache npm cache folder
        uses: actions/cache@v1
        env:
          cache-name: npm-cache
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
            ${{ runner.os }}-

      - name: Cache node modules folder
        uses: actions/cache@v1
        env:
          cache-name: node-modules-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Print branch name
        run: echo ${GITHUB_REF##*/}   

      - name: Build Ophanim application
        run: npm run build:$BUILD_BRANCH

      - name: Run unit tests
        run: npm run test

      - name: Run code linters
        run: npm run lint

      - name: Check code formatting
        run: npm run format:check

      - name: copy dist files to docker directory
        run: |
          cp -r dist nginxDockerFiles/files/        

      - name: Build nginx docker container
        run: |
          docker build ./nginxDockerFiles -t timbergrove/op2nginxfe:latest

      - name: Login, build and push to docker hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker tag timbergrove/op2nginxfe:latest timbergrove/op2nginxfe:${GITHUB_REF#refs/tags/}
          docker push timbergrove/op2nginxfe:latest
          docker push timbergrove/op2nginxfe:${GITHUB_REF#refs/tags/}
